name: Package and Release

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker command
        run: |
          chmod +x build.sh
          docker run --rm -v ${PWD}:/protonvpn-bin archlinux su - -c"/protonvpn-bin/build.sh"

      - name: Archive dist folder
        uses: actions/upload-artifact@v4
        with:
          name: protonvpn-bin
          path: protonvpn-bin-*.tar.zst

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: ./protonvpn-bin-*.tar.zst